Controllers/CartController.cs
using LaptopStore.Data.Interfaces;
using LaptopStore.Data.Models;
using LaptopStore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace LaptopStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ILaptops _laptopRepository;
        private readonly Cart _cart;

        public CartController(ILaptops laptopRepository, Cart cart)
        {
            _laptopRepository = laptopRepository;
            _cart = cart;
        }

        public ViewResult Index()
        {
            var items = _cart.GetCartItems();
            _cart.ListCartItems = items;
            _cart.itemsCount = items.Count();

            var obj = new CartViewModel
            {
                cart = _cart
            };

            return View(obj);
        }

        public RedirectToActionResult AddToCart(long id)
        {
            var item = _laptopRepository.GetAll().Single(i => i.id == id);
            if(item != null)
            {
                _cart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult DeleteFromCart(long id)
        {
            var item = _cart.GetCartItems().Single(i => i.id == id);
            if (item != null)
            {
                _cart.DeleteFromCart(item);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult Clear(string cartId)
        {
            var items = _cart.GetCartItems().Where(i => i.CartId == cartId);
            foreach (var item in items)
            {
                _cart.DeleteFromCart(item);
            }

            return RedirectToAction("Index");
        }

    }
}

Controllers/LaptopsController.cs
using LaptopStore.Data.Interfaces;
using LaptopStore.Data.Models;
using LaptopStore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace LaptopStore.Controllers
{
    public class LaptopsController : Controller
    {
        private readonly ILaptops _allLaptops;
        private readonly ICategory _allCategories;
        

        public LaptopsController(ILaptops allLaptops, ICategory allCategories)
        {
            _allLaptops = allLaptops;
            _allCategories = allCategories;
        }

        [Route("Laptops/List")]
        [Route("Laptops/List/{category}")]
        public ViewResult List(string category)
        {

            IQueryable<Laptop> laptops = GetLaptopsByCategory(category);
            string currCategory = GetCategory(laptops);

            var laptopObj = new LaptopListViewModel
            {
                allLaptops = laptops ?? _allLaptops.GetAll().OrderBy(i => i.id),
                currCategory = currCategory
            };

            ViewBag.Title = "Laptops";
            return View(laptopObj);
        }

        [Route("Laptops/LaptopDetails")]
        public ViewResult LaptopDetails(long id)
        {

            Laptop laptop = _allLaptops.GetObjectLaptop(id);

            ViewBag.Title = "Details";
            return View(laptop);
        }

        private IQueryable<Laptop> GetLaptopsByCategory(string category)
        {
            IQueryable<Laptop> laptops = null;
            if (!string.IsNullOrEmpty(category))
            {
                laptops = _allLaptops.GetAll().Where(x => x.Category.categoryName.ToLower().Equals(category.ToLower())).OrderBy(i => i.id);
                if (laptops.FirstOrDefault() == null)
                {
                    laptops = null;
                }
            }
            
            return laptops;
        }

        private string GetCategory(IEnumerable<Laptop> laptops)
        {
            return laptops != null ? _allCategories.GetCategoryByLaptop(laptops.FirstOrDefault()).categoryName : null;
        }

    }
}

Controllers/PrivacyController.cs
using LaptopStore.Data.Models;
using LaptopStore.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LaptopStore.Controllers
{
    public class PrivacyController : Controller
    {
        
        public ViewResult Index()
        {
            var privacyPolicy = new Privacy { privacy = "Use this page to detail your site's Privacy policy." };
            return View(privacyPolicy);
        }
    }
}

Controllers/ProfileController.cs
using System.Threading.Tasks;
using LaptopStore.ViewModels;
using LaptopStore.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using LaptopStore.Data.Models;
using System.Linq;

namespace LaptopStore.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IProfiles _profiles;

        public ProfileController(IProfiles profiles)
        {
            _profiles = profiles;
        }

        
        public async Task<IActionResult> ProfileInfo()
        {
            var email = User.Identity?.Name;
            var response = await _profiles.GetProfile(email);
            if (response.StatusCode == Data.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return RedirectToAction("Login","Account");
        }

        [HttpGet]
        public IActionResult Save() => PartialView();

        [HttpPost]
        public async Task<IActionResult> Save(Profile model)
        {
            if (ModelState.IsValid)
            {
                if (model.id != 0)
                {
                    await _profiles.Update(model);
                }
                return RedirectToAction("ProfileInfo");
            }
            return RedirectToAction("ProfileInfo");
        }
    }
}

Views/Shared/Laptops.cshtml
@model Laptop
<div class="col-md-4" style="min-width:380px;">
    <div class="card mb-3 box-shadow" style="height:95%; min-width:350px; display: block;">
        <a asp-controller="Laptops" asp-action="LaptopDetails" asp-route-id="@Model.id">
            <img class="card-link" alt="@Model.name [100%x260]"  style="height: 40%; width: 100%; display: block;" src="@Model.imgUrl" data-holder-rendered="true">
        </a>
        <div class="card-body" style="height: 50%; width: 100%; display: block;" >
            <h2>@Model.name</h2>
            <p class="card-text">@Model.shortDesc</p>
        </div>
        <div class="card-footer align-bottom" style="height: 10%; width: 100%; display: block;">
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-secondary" asp-controller="Laptops" asp-action="LaptopDetails" asp-route-id="@Model.id">More</a>
                    <a class="btn btn-sm btn-outline-warning" asp-controller="Cart" asp-action="AddToCart" asp-route-id="@Model.id">Add to cart</a>
                </div>
                <h5 class="text-muted">Price: @Model.price.ToString("c", System.Globalization.CultureInfo.GetCultureInfo("en-us"))</h5>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using LaptopStore.ViewModels
<!DOCTYPE html>
<html lang="en">

    <div class="modal fade" id="signIn">
        <div class="modal-dialog">
            <div class="modal-content" id="login">
                <div class="face front">
                    <div class="card-body">
                        <!-- Header -->
                        <div class="form-header primary-color">
                            <h3 class="font-weight-500 my-2 py-1"><i class="fas fa-sign-in-alt"></i> Log in</h3>
                        </div>
                        @Html.Partial("~/Views/Account/Login.cshtml", new LoginViewModel())
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between">
                            <a type="button" tabIndex="-1" data-card="my-card" 
                                onclick="toRegister()">create account</a>
                            <!--<a href="#" class="grey-text" tabIndex="-2">forgot password?</a>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-content" id="register" hidden="hidden">
                <div class="face back">
                    <div class="card-body">
                        <!-- Header -->
                        <div class="form-header primary-color">
                            <h3 class="font-weight-500 my-2 py-1"><i class="fas fa-plus"></i> Create Account</h3>
                        </div>
                        @Html.Partial("~/Views/Account/Register.cshtml", new RegisterViewModel())
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-end">
                            <a type="button" data-card="my-card" tabIndex="-3" onclick="toLogin()">back to login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaptopStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bigTable.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LaptopStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ml-auto">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="my-2 my-md-0 mr-md-3">
                                <button class="btn btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#singIn" 
                                    onclick="$('#signIn').modal('show')">Sign in</button> 
                            </li>
                        } 
                        else
                        {
                            <li class="nav-item dropdown my-2 my-md-0 mr-md-3">
                                <a class="nav-link text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" asp-controller="" asp-action="">Account</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="ProfileInfo">Info</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Log out</a>
                                </div>
                            </li>
                        }
                        <li class="my-2 my-md-0 mr-md-3">
                            <a class="btn btn-outline-warning" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Favorites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Privacy" asp-action="Index">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" asp-controller="Laptops" asp-action="List">Laptops</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Laptops" asp-action="List" asp-route-category="All">All</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Laptops" asp-action="List" asp-route-category="Gaming">Gaming</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Laptops" asp-action="List" asp-route-category="Ultrathin">Ultrathin</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Laptops" asp-action="List" asp-route-category="Office">Office</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Laptops" asp-action="List" asp-route-category="Transformer">Transformer</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        <main role="main" class="pb-3">
            <h1>@ViewData["Title"]</h1>
            <hr />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LaptopStore - <a asp-area="" asp-controller="Privacy" asp-action="Index">Privacy</a>
        </div>
    </footer>

    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/LoginAndRegister.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>