Controllers/OrderController.cs
using LaptopStore.Data.Interfaces;
using LaptopStore.Data.Models;
using LaptopStore.ViewModels;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace LaptopStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrders orders;
        private readonly IUsers users;
        private readonly Cart cart;

        public OrderController(IOrders orders, IUsers users, Cart cart)
        {
            this.orders = orders;
            this.users = users;
            this.cart = cart;
        }

        public IActionResult Checkout()
        {
            var email = User.Identity?.Name;
            if (email != null)
            {
                return View();
            }
            return RedirectToAction("Login","Account");
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            cart.ListCartItems = cart.GetCartItems();

            if(cart.ListCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your shopping cart must contain items");
            }

            if (ModelState.IsValid)
            {
                var email = User.Identity?.Name;
                if (email != null)
                {
                    Order newOrder = order;
                    
                    var user = await users.GetAll().FirstOrDefaultAsync(x => x.email == email);
                    newOrder.userId = user.id;

                    await orders.Create(newOrder);

                    foreach (var item in cart.ListCartItems)
                    {
                        cart.DeleteFromCart(item);
                    }
                    return RedirectToAction("ProfileInfo","Profile");
                }
            }

            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteOrder(long id)
        {
            var order = orders.GetAll().FirstOrDefault(x => x.id == id);
            await orders.Delete(order);
            return RedirectToAction("ProfileInfo", "Profile");
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Order successfully processed";
            return View();
        }

    }
}

Controllers/UserController.cs
using System.Linq;
using System.Threading.Tasks;
using LaptopStore.Data.Interfaces;
using LaptopStore.Data.Models;
using LaptopStore.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LaptopStore.Controllers
{
    public class UserController : Controller
    {
        private readonly IUsers _users;

        public UserController(IUsers users)
        {
            _users = users;
        }
        
        public PartialViewResult GetUsers()
        {
            var userList = GetAllUsers();

            return PartialView(userList);
        }

        public PartialViewResult UserOrders()
        {
            var email = User.Identity?.Name;
            if (email != null)
            {
                var orders = GetUserOrders(email);
                return PartialView(orders);
            }

            return PartialView();
        }

        public async Task<IActionResult> DeleteUser(long id)
        {
            //User user = _users.GetAll().Single(x => x.id == id);
            await _users.Delete(id);
            
            return RedirectToAction("ProfileInfo", "Profile");
        }

        private OrderListViewModel GetUserOrders(string email)
        {
            var orders = new OrderListViewModel()
            {
                userOrders = _users.UserOrders(email)
            };

            return orders;
        }

        private UserListViewModel GetAllUsers()
        {
            var userList = new UserListViewModel()
            {
                allUsers = _users.GetAll().OrderBy(i => i.id)
            };

            return userList;
        }

    }
}

Views/User/GetUsers.cshtml
@using LaptopStore.Data.Models
@using LaptopStore.ViewModels
@model UserListViewModel

@{
    Layout = "";
}
<h5 class="card-title">Users</h5>
<hr/>
<div class="card mb-4 box-shadow text-center">
    <div class="big-table">
        <table class="table table-striped">
            <thead class="table-light">
            <tr style="width:100%">
                <th scope="col" style="width:10%">Id</th>
                <th scope="col" style="width:30%">Login</th>
                <th scope="col" style="width:30%">Email</th>
                <th scope="col" style="width:20%">Role</th>
                <th scope="col" style="width:10%"></th>
            </tr>
            </thead>
            <tbody>
            @foreach (User user in @Model.allUsers)
            {
                <tr style="width:100%">
                    <td style="width:10%">@user.id</td>
                    <td style="width:30%">@user.loginName</td>
                    <td style="width:30%">@user.email</td>
                    <td style="width:20%">@user.role</td>
                    <td style="width:10%">
                        <form asp-action="DeleteUser" asp-controller="User" asp-route-id="@user.id" method="post">
                            <button type="submit" class="btn btn-sm btn-danger">
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>
<!--
section pageScripts
{
    <script>
        function model() {
            return {
                name: $('input#Name').val(),
                role: $('#selectRoleId').val(),
                address: $('textarea#Address').val(),
            }
        };
        
       $('#saveBtn').on('click', function () {
           $.ajax({
               url: '@Url.Action("Save")',
               type: 'POST',
               data: model(),
           }) 
      });
    </script>
}
-->

Views/User/UserOrders.cshtml
@using LaptopStore.Data.Models
@using LaptopStore.ViewModels
@model OrderListViewModel

@{
    Layout = "";
}

@if (Model.userOrders.Count() != 0)
{
    <h5 class="card-title">Orders</h5>
    <hr/>
}
@foreach (Order order in Model.userOrders)
{
    <div class="card mb-4 box-shadow text-center">
        <div class="card-header">
        <h5 class="my-0 font-weight-normal">Order: #@order.id</h5>
        </div>
        <div class="card-body">
            @foreach (OrderDetail orderDetail in order.orderDetails)
            {
            <table>
                <tr style="width: 100%; display: block;">
                    <td style="width: 30%;">
                        <img class="card-img-top" alt="@orderDetail.laptop.name [30%]"  
                            src="@orderDetail.laptop.imgUrl" data-holder-rendered="true">
                    </td>
                    <td style="width: 70%;">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>@orderDetail.laptop.name</li>
                            <li>@orderDetail.laptop.price.ToString("c", System.Globalization.CultureInfo.GetCultureInfo("en-us"))</li>
                        </ul>
                    </td>
                </tr>
            </table>
            <hr/>
            }
        <h5 class="my-0 font-weight-normal">Total: 
            @order.orderDetails.Sum(o => (decimal) o.price).ToString("c", System.Globalization.CultureInfo.GetCultureInfo("en-us"))
        </h5>
        </div>
        <div class="card-footer">
            <form asp-action="DeleteOrder" asp-controller="Order" asp-route-id="@order.id" method="post">
                <button type="submit" class="btn btn-sm btn-danger">
                    Cancel the order
                </button>
            </form>
        </div>
    </div>
}